# Generated by Django 5.1.4 on 2024-12-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarPark",  # Update to CarPark
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_park_no", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("x_coord", models.FloatField()),
                ("y_coord", models.FloatField()),
                ("car_park_type", models.CharField(max_length=150)),
                ("type_of_parking_system", models.CharField(max_length=150)),
                ("short_term_parking", models.CharField(max_length=200)),
                ("free_parking", models.BooleanField()),
                ("night_parking", models.BooleanField()),
                ("car_park_decks", models.IntegerField()),
                ("gantry_height", models.FloatField()),
                ("car_park_basement", models.BooleanField()),

            ],
        ),
    ]
