# Generated by Django 5.1.4 on 2024-12-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carparks", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="carpark",  # Update to CarPark
            unique_together={
                ("car_park_no", "address", "car_park_type", "gantry_height", "type_of_parking_system", "short_term_parking")
            },
        ),
    ]

