# Generated by Django 5.1.4 on 2025-01-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0002_alter_carpark_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carpark',
            unique_together={('car_park_no', 'address', 'car_park_type', 'gantry_height', 'type_of_parking_system')},
        ),
        migrations.AlterField(
            model_name='carpark',
            name='short_term_parking',
            field=models.BooleanField(),
        ),
    ]
