# Generated by Django 5.2.5 on 2025-08-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0003_alter_carpark_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpark',
            name='free_parking',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='short_term_parking',
            field=models.CharField(max_length=100),
        ),
    ]
