# Generated by Django 5.2.5 on 2025-08-10 20:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carparks', '0004_alter_carpark_free_parking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpark',
            options={'ordering': ['address', 'car_park_no'], 'verbose_name': 'Car Park', 'verbose_name_plural': 'Car Parks'},
        ),
        migrations.AddField(
            model_name='carpark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='address',
            field=models.CharField(help_text='Full address of the car park', max_length=255),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='car_park_basement',
            field=models.BooleanField(default=False, help_text='Whether the car park has a basement'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='car_park_decks',
            field=models.IntegerField(help_text='Number of parking decks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='car_park_no',
            field=models.CharField(help_text='Unique identifier for the car park', max_length=100),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='car_park_type',
            field=models.CharField(help_text='Type of car park (e.g., SURFACE CAR PARK, MULTI-STOREY CAR PARK)', max_length=150),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='free_parking',
            field=models.CharField(help_text='Free parking availability (e.g., NO, SUN & PH FR 7AM-10.30PM)', max_length=100),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='gantry_height',
            field=models.FloatField(help_text='Height of the gantry in meters', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='night_parking',
            field=models.BooleanField(default=False, help_text='Whether night parking is available'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='short_term_parking',
            field=models.CharField(help_text='Short term parking availability (e.g., WHOLE DAY, 7AM-7PM, NO)', max_length=100),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='type_of_parking_system',
            field=models.CharField(help_text='Type of parking system used', max_length=150),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='x_coord',
            field=models.FloatField(help_text='X coordinate of the car park location'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='y_coord',
            field=models.FloatField(help_text='Y coordinate of the car park location'),
        ),
    ]
