name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # GitHub repository secrets (make sure these exist)
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}            # account token
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}  # project id
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}  # "web" service id
      RAILWAY_ENVIRONMENT: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # No 'use', no '--project'. The project is taken from env.
      - name: Deploy (Dockerfile) to Railway
        run: |
          railway up --ci --detach \
            --service "$RAILWAY_SERVICE_ID" \
            --environment "$RAILWAY_ENVIRONMENT"

      - name: Run migrations
        run: |
          railway run --service "$RAILWAY_SERVICE_ID" \
            --environment "$RAILWAY_ENVIRONMENT" \
            python manage.py migrate --noinput

      - name: Collect static
        run: |
          railway run --service "$RAILWAY_SERVICE_ID" \
            --environment "$RAILWAY_ENVIRONMENT" \
            python manage.py collectstatic --noinput

      - name: Smoke test /healthz (retry)
        run: |
          set -e
          for i in $(seq 1 10); do
            echo "Try #$i: hitting internal healthz..."
            if railway run --service "$RAILWAY_SERVICE_ID" \
                 --environment "$RAILWAY_ENVIRONMENT" \
                 bash -lc 'curl -fsS http://127.0.0.1:${PORT:-8000}/healthz/'; then
              echo "healthz OK"; exit 0
            fi
            sleep 3
          done
          echo "healthz failed"; exit 1
