name: Deploy to Railway (Docker + Django)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy to Railway
        run: railway up --detach

      - name: Run migrations
        run: railway run python manage.py migrate --noinput

      - name: Collect static
        run: railway run python manage.py collectstatic --noinput

      - name: Create superuser (optional)
        if: ${{ env.DJANGO_SUPERUSER_USERNAME != '' }}
        run: |
          railway run python - <<'PY'
          import os, django
          os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")
          django.setup()
          from django.contrib.auth import get_user_model
          User = get_user_model()
          if not User.objects.filter(username=os.environ["DJANGO_SUPERUSER_USERNAME"]).exists():
              User.objects.create_superuser(
                  username=os.environ["DJANGO_SUPERUSER_USERNAME"],
                  email=os.environ["DJANGO_SUPERUSER_EMAIL"],
                  password=os.environ["DJANGO_SUPERUSER_PASSWORD"]
              )
              print("Superuser created")
          else:
              print("Superuser exists")
          PY
