name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Authenticate & Link Railway
        shell: bash
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway status || true

      - name: Deploy to Railway
        shell: bash
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          railway up --ci --service ${{ secrets.RAILWAY_SERVICE_ID }} --detach | cat

      - name: Smoke test deployment
        run: |
          echo "Running smoke test..."
          curl -f https://${{ secrets.RAILWAY_PUBLIC_URL }}/healthz/ || exit 1
          echo "✅ Health check passed!"
