name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Authenticate & Link Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway status || true

      - name: Deploy to Railway
        run: |
          railway up --detach --service ${{ secrets.RAILWAY_SERVICE_ID }}

      - name: Check deployment status
        run: |
          echo "✅ Deployment initiated successfully!"
          echo "Check your Railway dashboard: https://railway.app/project/5000d90d-4a5a-4c61-92d3-e115a3b36697"
